[workspace]
resolver = "2"
members = ["bins/miniplan-cli", "crates/miniplan"]

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "EUPL-1.2"
repository = "https://github.com/sunsided/miniplan"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
keywords = ["pddl", "planning", "ai", "scheduling"]
categories = ["science"]

[workspace.dependencies]
anyhow = "1"
assert_cmd = "2"
bitflags = "2"
clap = { version = "4", features = ["derive"] }
fixedbitset = "0.5"
humantime = "2"
indexmap = "2"
miniplan = { version = "0.1.1", path = "crates/miniplan" }
pddl = "0.2.0"
pretty_assertions = "1"
rustc-hash = "2"
serde_json = "1"
tempfile = "3"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
